---
# roles/kube_master/defaults/main.yml

kubernetes_version: "1.36.1"
kube_apiserver_secure_port: 6443
kube_apiserver_service_node_port_range: "30000-32767"
kube_apiserver_event_ttl: "1h"
kube_apiserver_audit_log_maxage: 30
kube_apiserver_audit_log_maxbackup: 10
kube_apiserver_audit_log_maxsize: 100
kube_apiserver_admission_plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
kube_apiserver_authorization_mode: "Node,RBAC"
kube_controller_manager_secure_port: 10257
kube_scheduler_secure_port: 10259
