---
# roles/kubelet/handlers/main.yml

- name: daemon reload
  listen: containerd config changed
  systemd:
    daemon_reload: yes

- name: restart containerd
  listen: containerd config changed
  systemd:
    name: containerd
    state: restarted

- name: daemon reload
  listen: kubelet config changed
  systemd:
    daemon_reload: yes

- name: restart kubelet
  listen: kubelet config changed
  systemd:
    name: kubelet
    state: restarted
